#Definition du nom 

name: Manipuler des variables

#Trigger : Push sur "main" et manuel
on: 
  push:
    branches: 
      - main
  workflow_dispatch:

# Creation de variable d'env custom
env: 
  FORMATION_CENTER: "DIGITAL CITY"


# Job qui manipule des varibles et secrets
jobs:
  use_variables:
    runs-on: ubuntu-latest
    steps:
      - name: confirm deploy
        #Example d'une variable d'env pré-configuré
        run: echo "Deploiment de la branches $GITHUB_REF"
      - name: formation location
        # Exemple d'une variable d'env custom
        run: |
          echo "Lieux de formation : $FORMATION_CENTER"
      - name: variable github
        run: |
          echo "Project name : ${{ vars.PROJECT_NAME}}"
          echo "User password : ${{ secrets.USER_PASSWORD}}"
          echo "Mode selected : ${{ vars.MODE}}"
